// This file is generated by Sapper — do not edit it!
export const routes = [
	
];

if (module.hot) {
	import('C:/Users/M0RGAN/Desktop/BankCient/NommisteBank-client/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}